### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by Rasipuram** [HLTCHKUST/MoEL#1]
Dear Authors,

Thank you for providing code. 

I want to use the trained model to generate responses for a new text. Is there is a way to do the inference part for a new text.

**Comment by manzar96** [comment]
Did you finally find the way?

**Comment by zlinao** [comment]
Hi, sorry for late reply. I added a simple interact script. Try the following command:
python3 interact.py --model experts  --label_smoothing --noam --emb_dim 300 --hidden_dim 300 --hop 1 --heads 2 --topk 5 --cuda --pretrain_emb --softmax --basic_learner --save_path save/checkpoint

**Comment by Rasipuram** [comment]
Thank you for sharing the code. But got this error while running the interact.py code

TypeError: 'Transformer_experts' object is not subscriptable

Requirements are installed. 

Thanks and regards

**Comment by zlinao** [comment]
Hi, can you share the full error message?

**Comment by Rasipuram** [comment]
Please find the message.loading weights
Traceback (most recent call last):
  File "interact.py", line 69, in <module>
    model = Transformer_experts(vocab,decoder_number=program_number, model_file_path=config.save_path, is_eval=True)
  File "/home/ubuntu/Desktop/Sowmya/Conversation/MoEL_NO_DATA/model/transformer_mulexpert.py", line 363, in __init__
    self.encoder.load_state_dict(state['encoder_state_dict'])
TypeError: 'Transformer_experts' object is not subscriptable

Thanks and regards

**Comment by zlinao** [comment]
What command did you run? Did you give the correct model checkpoint? python3 interact.py --model experts --label_smoothing --noam --emb_dim 300 --hidden_dim 300 --hop 1 --heads 2 --topk 5 --cuda --pretrain_emb --softmax --basic_learner --save_path save/checkpoint

**Comment by Rasipuram** [comment]
Yes. It worked. Thank you very much.
