### ISSUE TITLE
about metric

### ISSUE THREAD

**Issue by A-Rain** [HLTCHKUST/MoEL#2]
Hi,

This is a very nice work! While there are some detials that I'm confused:
1. Does the Bleu means average Bleu score like the original paper "Towards Empathetic Open-domain Conversation Models: a New Benchmark and Dataset"?
2. Why don't you compare the basline result in "Towards Empathetic Open-domain Conversation Models: a New Benchmark and Dataset"?

**Comment by zlinao** [comment]
Hi,

Thanks for reading our work.

1. The BLEU score (Papineni et al., 2002) used in this paper is different from average BLEU.
2. The ACL version of "Towards Empathetic Open-domain Conversation Models: a New Benchmark and Dataset" was not available when we submit this paper.  Instead, we used the dataset from its ICLR submission (https://openreview.net/pdf?id=HyesW2C9YQ), where the authors pretrained their models on a dump of 1.7 billion Reddit conversations.

**Comment by A-Rain** [comment]
Thank you for the reply, so did you use Bleu-2 as the Bleu score in this paper?

**Comment by zlinao** [comment]
The BLEU (https://www.aclweb.org/anthology/P02-1040.pdf) is the combination of BLEU1-4 with length penalty. We used the implementation of the MOSES ulti-bleu.perl script.
