### ISSUE TITLE
Questions about code reproduction

### ISSUE THREAD

**Issue by Lireanstar** [HLTCHKUST/MoEL#6]
When I ran the code locally, I successfully ran the program according to the README.md, but due to the patience of the program, my program ended early and entered the testing stage. I ran TRS and MultiTRS. The two programs were about 16000. When entering the testing stage when stepping, is this normal?
When I ran the MoEL, I finally got the result:
EVAL	Loss	        PPL	        Accuracy	Bleu_g	Bleu_b
test	        3 .7540	42.6931	0.37  	2.85 	2.87
How can I set up to reproduce the results of the paper?

Thanks

**Comment by wangjs9** [comment]
Can you reproduce the results TRS or MultiTRS? (I face the same problem and I could not even reproduce these two models either :(

**Comment by wenxiong-xu** [comment]
> Can you reproduce the results TRS or MultiTRS? (I face the same problem and I could not even reproduce these two models either :(
I faced the same question. Have you found any solution?

**Comment by zlinao** [comment]
Hi all, we had tested our code one year ago with a single 1080Ti GPU by following the instructions in the README.  All the result should be reproducible with same machine and environment. 

You are also welcome to report any results obtained from this repo.
